{% set name = "passlib" %}
{% set version = "1.7.3" %}
{% set bundle = "tar.gz" %}
{% set hash = "0fe8b86a900b2885fed00cf5e96f040c7abd61496d65dec4c814e462f8499d8a" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - argon2-cffi >=19.2.0
    - bcrypt >=3.1.0
    - cryptography

test:
  imports:
    - passlib
    - passlib._setup
    - passlib.crypto
    - passlib.crypto._blowfish
    - passlib.crypto.scrypt
    - passlib.ext
    - passlib.ext.django
    - passlib.handlers
    - passlib.tests
    - passlib.utils
    - passlib.utils.compat

about:
  home: https://bitbucket.org/ecollins/passlib
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: comprehensive password hashing framework supporting over 30 schemes
  dev_url: https://bitbucket.org/ecollins/passlib/src
  doc_url: https://bitbucket.org/ecollins/passlib/wiki/Home

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
