{% set name = "passlib" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a83d34f53dc9b17aa42c9a35c3fbcc5120f3fcb07f7f8721ec45e6a27be347fc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argon2_cffi >=16.2
    - bcrypt >=3.1.0
    - cryptography

test:
  imports:
    - passlib
    - passlib._setup
    {% if version >= "1.7.1" %}
    - passlib.crypto
    - passlib.crypto._blowfish
    - passlib.crypto.scrypt
    {% endif %}
    - passlib.ext
    - passlib.ext.django
    - passlib.handlers
    - passlib.tests
    - passlib.utils
    - passlib.utils.compat

about:
  home: https://bitbucket.org/ecollins/passlib
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'comprehensive password hashing framework supporting over 30 schemes'
  dev_url: https://bitbucket.org/ecollins/passlib/src
  doc_url: https://bitbucket.org/ecollins/passlib/wiki/Home

extra:
  recipe-maintainers:
    - pmlandwehr
