travis:
  secure:
    BINSTAR_TOKEN: nF/cdSNo9RUC5kcUUFJhVZHZkZ4fdjVitKhnWmSSSvqb7sm7HxHYbCYZXCprw6pXV7R8jyE7NJZdw2jnVRR7tpGC6uDW41KdfBaLyp/80qCY3nSmC7iwC9sNan+qMtOWhxCt2WD2p3m0KwPIYPzAw7Dym4Hj6GhMl2Q5uP0BoCsEvWdzZ6/fnPjeOq1bRTM95SdTweJnr79nVd6XHNNinRLQH/JCKnHl5pcOm3rzw5mMRkfo3Y5EzwG53Xv0QZmjhV+IRD6rY3IYmUzRo89AVfB9Qnh4LinhTbmB/i2QLnaXmBjahzEhXjdvwhYcIf8hyY/fhj5fxaFM5xVigA/dk4VymxEhprwS6VuUT8AJXQEIeWOfAIXSJLIni44a+dI2iYn+YMWCOq5Jj/dkE7S9eV/8fAlMF+1ojha/LREmq506Mi+rRpZaprOEUoIBCQPqTefLZ/hnGwnNhEfvZ3K2DzUYuM4WyH4Xs9NLzNqcnP2nimOuYTzC5LBPxj6WEHXNUgJ29RyU3UefK9Vnj9yd3YibNiiACbX3uukTX0bov8bEqysExCnFeo3NXnbMRE+yzoRiMiTL+FAc7O8rzmSHG40070lItmZBVWWSW2GXpYC1EG5dt8AEJj07gROV7kgeBsllXUcP1GykGpyF4C6tcdk/57DwWolAomxoLQfr/ns=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
